# Generated by Django 5.0.4 on 2025-02-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='name_dean',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='name_faculty',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='tel_dean',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='name_speciality',
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='FIT', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='readerspeciality',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='name',
            field=models.CharField(default='Taras', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speciality',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='users.faculty'),
        ),
    ]
