# Generated by Django 5.0.4 on 2025-03-26 13:37

import django.db.models.deletion
import logbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineservicehistory',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('returned', 'Повернуто')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='loan_code',
            field=models.CharField(editable=False, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lineservicehistory',
            name='date_when_should_return',
            field=models.DateField(default=logbook.models.default_return_date),
        ),
        migrations.AlterField(
            model_name='lineservicehistory',
            name='date_when_was_taken',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lineservicehistory',
            name='service_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_items', to='logbook.servicehistory'),
        ),
    ]
