# Generated by Django 5.0.4 on 2025-03-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_lineservicehistory_status_servicehistory_loan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='loan_code',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
    ]
