# Generated by Django 5.0.4 on 2025-04-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reminder', 'Нагадування'), ('warning', 'Попередження'), ('block', 'Блокування')], default='reminder', max_length=10),
        ),
    ]
