# Generated by Django 5.0.4 on 2025-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reminder', 'Нагадування'), ('warning', 'Попередження'), ('block', 'Блокування'), ('unblock', 'Розблокування')], default='reminder', max_length=10),
        ),
    ]
